### ISSUE TITLE
可以进游戏吗

### ISSUE THREAD

**Issue by krrr** [Admirepowered/genshin#1]
想问下，这个私服服务端完整吗，可否真的进入游戏

**Comment by Admirepowered** [comment]
暂时还不能，只做了HTTP部分，KCP部分需要Protobuf，Go的Protobuf还不会写，在等人研究透了再写，不过我这里有Node.js版本的

**Comment by krrr** [comment]
是ragezone论坛下载的吗，我也下了一份还没运行，那个作者说要2.5或2.6的beta客户端……
我也很有兴趣想参与下可惜我不会go……js倒是会的

**Comment by Admirepowered** [comment]
企鹅群833315230 工程量太大，所以几乎没啥进展

**Comment by MoonShadowIllusion** [comment]
> 暂时还不能，只做了HTTP部分，KCP部分需要Protobuf，Go的Protobuf还不会写，在等人研究透了再写，不过我这里有Node.js版本的

能让我看看吗
